[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_GEMINI_API_KEY = "your_gemini_api_key_here"

[context.deploy-preview.environment]
  VITE_GEMINI_API_KEY = "your_gemini_api_key_here"

[context.branch-deploy.environment]
  VITE_GEMINI_API_KEY = "your_gemini_api_key_here"